#!/bin/bash
read -p "enter the user name " user
pat='^[A-Za-z]{3,}$' 
pat1='[a-zA-Z]{3,}$'
#for email id verification
pat2='^[a-zA-Z0-9]+([.\-+]?[a-zA-Z0-9]+)*[@][a-z]{2,5}[.]?[a-z]{2,3}([.][a-z]{2})*$'
number='^(91[ ])*[0-9]{10}$'
password='^[a-zA-Z]{8,}$'
pat6='^[A-Z]{1,}[a-zA-Z]{7,}$'
pat7='^[A-Z]{1,}[a-zA-Z]{7,}[0-9]{1,}$'
pat8='^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%+]).{8,}$'
if [[ $user =~ $pat8 ]]
then
echo "vaild"
else
echo "not valid"
fi
